{
    'name': 'Company Management',
    'version': '18.0.0.1',
    'summary': 'Company Management system to manage Company Data',
    'author': 'Codetrade.io',
    'depends': ['mail','website','sale','product'],
    'website':'https://www.codetrade.io/',
    'category':"Company Management",
    'assets': {
        'web.assets_backend': [
        'codetrade_module/static/src/js/open_wizard_js.js',
        'codetrade_module/static/src/js/notification.js',
        'codetrade_module/static/src/js/sale_quotation_email.js',
        'codetrade_module/static/src/xml/save_button_employee.xml',
        'codetrade_module/static/src/xml/button.xml'
        ],
    },
    'data': [
        'data/ir_cron_data.xml',
        'views/ir_action_data.xml',
        'security/company_security_groups.xml',
        'security/ir.model.access.csv',
        'views/email_templates.xml',
        'views/birthday_email_template.xml',
        'views/company_views.xml',
        'views/hr_details_template.xml',
        'views/employee_form_template.xml',
        'views/employee_full_details_template.xml',
        'views/form_view_button.xml',
        'views/employee_details_template.xml',
        'views/intern_details_template.xml',
        'views/codetrade_home_template.xml',
        'views/sale_model_view.xml',
        'wizard/company_office_wizard.xml',
        'wizard/company_intern_wizard.xml',
        'views/school_student_views.xml',
        'views/company_menuitems.xml',
    ],
    'installable': True,
    'license': 'LGPL-3',
}
