{
    'name': 'Hospital Management',
    'version': '18.0.0.1',
    'summary': 'Hospital Management system to manage Patient Data',
    'author': 'Codetrade.io',
    'depends': [],
    'website': 'https://www.codetrade.io/',
    'category': "Hospital Management",
    'data': [
        'security/ir.model.access.csv',
        'views/menuitems.xml',
        'views/patient_views.xml',
        'report/report_paper_format.xml',
        'report/patient_report.xml',
        'report/patient_details_report.xml',
        'views/appointment_views.xml',
        'data/report_server_action.xml',
        'report/appointment_report.xml',
        'views/prescription_views.xml',
        'data/ir.sequence.xml',
        'report/prescription_report.xml',
        'views/administration_views.xml',
        'wizard/bed_transfer_wizard_view.xml',
        'views/intensive_patient_icu_view.xml',
        'views/intensive_apache_score_views.xml',
        'views/intensive_ecg_views.xml',
        'views/intensive_gcs_views.xml',
        'views/pediatrics_symptoms_views.xml'
    ],
    'installable': True,
    'license': 'LGPL-3',
}
