from . import patient
from . import appointments
from . import prescription
from . import administration
from . import intensive_care
from . import pediatrics
from . import newborn_baby
from . import laboratory
from . import today_lab_draft_request
from . import patient_ambulatory
from . import surgery
from . import medical_service
from . import medicament_list
from . import patient_evaluation
